(function(){
  const protocol='hios-plugin-app/v1'; const canvas=document.getElementById('canvas'); const ctx=canvas.getContext('2d');
  const $=id=>document.getElementById(id); const state={canvas:{width:1080,height:1350,background:'#ffffff',dpi:72},layers:[]}; let selectedId=''; let zoom=0.72; let drag=null;
  const post=(type,payload={})=>parent.postMessage({protocol,type,payload},'*');
  function serializableState(){return {canvas:clone(state.canvas),layers:state.layers.map(({image,...layer})=>clone(layer))};}
  function notify(){post('state',{state:serializableState()}); render();}
  function normalizeLayer(layer){return Object.assign({id:crypto.randomUUID(),type:'image',name:'图层',x:0,y:0,w:200,h:200,rotation:0,opacity:1,visible:true,src:'',text:'',fontSize:64,color:'#202936'},layer);}
  function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image(); image.onload=()=>resolve(image); image.onerror=reject; image.src=src;});}
  function drawLayer(layer){if(!layer.visible)return;ctx.save();ctx.globalAlpha=Number(layer.opacity??1);ctx.translate(layer.x+layer.w/2,layer.y+layer.h/2);ctx.rotate((layer.rotation||0)*Math.PI/180);if(layer.type==='text'){ctx.fillStyle=layer.color||'#202936';ctx.font=`700 ${layer.fontSize||64}px "Microsoft YaHei",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const words=String(layer.text||'文字').split('\n');const line=(layer.fontSize||64)*1.2;words.forEach((word,i)=>ctx.fillText(word,0,(i-(words.length-1)/2)*line,layer.w));}else if(layer.image){ctx.drawImage(layer.image,-layer.w/2,-layer.h/2,layer.w,layer.h);}ctx.restore();}
  function render(){canvas.width=state.canvas.width;canvas.height=state.canvas.height;ctx.fillStyle=state.canvas.background||'#fff';ctx.fillRect(0,0,canvas.width,canvas.height);state.layers.forEach(layer=>drawLayer(layer));canvas.style.width=`${Math.round(state.canvas.width*zoom)}px`;canvas.style.height=`${Math.round(state.canvas.height*zoom)}px`;renderLayers();renderProps();$('zoomLabel').textContent=`${Math.round(zoom*100)}%`;}
  function moveLayer(id,delta){const index=state.layers.findIndex(l=>l.id===id);const next=index+delta;if(index<0||next<0||next>=state.layers.length)return;[state.layers[index],state.layers[next]]=[state.layers[next],state.layers[index]];notify();}
  function renderLayers(){const box=$('layers');box.innerHTML='';state.layers.slice().reverse().forEach(layer=>{const item=document.createElement('div');item.className=`layer ${layer.id===selectedId?'active':''}`;item.innerHTML=`<span class="dot"></span><span class="name"></span><button class="layer-btn" title="上移">↑</button><button class="layer-btn" title="下移">↓</button>`;item.querySelector('.name').textContent=layer.name||'图层';item.onclick=()=>{selectedId=layer.id;render();};const buttons=item.querySelectorAll('.layer-btn');buttons[0].onclick=e=>{e.stopPropagation();moveLayer(layer.id,1)};buttons[1].onclick=e=>{e.stopPropagation();moveLayer(layer.id,-1)};box.appendChild(item);});}
  function selected(){return state.layers.find(layer=>layer.id===selectedId)||null;}
  function renderProps(){const layer=selected();$('emptyProps').hidden=!!layer;$('props').hidden=!layer;if(!layer)return;$('layerName').value=layer.name||'';$('layerX').value=Math.round(layer.x);$('layerY').value=Math.round(layer.y);$('layerW').value=Math.round(layer.w);$('layerH').value=Math.round(layer.h);$('layerOpacity').value=layer.opacity??1;$('textColorRow').hidden=layer.type!=='text';$('fontSizeRow').hidden=layer.type!=='text';if(layer.type==='text'){$('textColor').value=layer.color||'#202936';$('fontSize').value=layer.fontSize||64;}}
  function updateSelected(patch){const layer=selected();if(!layer)return;Object.assign(layer,patch);notify();}
  function fit(){const box=$('.canvas-wrap');zoom=Math.min((box.clientWidth-56)/state.canvas.width,(box.clientHeight-56)/state.canvas.height);zoom=Math.max(.05,Math.min(2,zoom));render();}
  function applyPreset(value){if(value==='custom')return;const [width,height]=value.split('x').map(Number);state.canvas.width=width;state.canvas.height=height;if(value==='2480x3508')state.canvas.dpi=300;$('width').value=width;$('height').value=height;$('dpi').value=state.canvas.dpi;notify();fit();}
  $('preset').onchange=e=>applyPreset(e.target.value);$('width').onchange=e=>{state.canvas.width=Math.max(64,Number(e.target.value)||1080);notify();};$('height').onchange=e=>{state.canvas.height=Math.max(64,Number(e.target.value)||1350);notify();};$('dpi').onchange=e=>{state.canvas.dpi=Math.max(1,Number(e.target.value)||72);notify();};$('background').oninput=e=>{state.canvas.background=e.target.value;notify();};
  $('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{for(const file of Array.from(e.target.files||[])){const src=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file);});const image=await loadImage(src);const scale=Math.min((state.canvas.width*.72)/image.width,(state.canvas.height*.55)/image.height,1);const layer=normalizeLayer({type:'image',name:file.name,x:(state.canvas.width-image.width*scale)/2,y:(state.canvas.height-image.height*scale)/2,w:image.width*scale,h:image.height*scale,src});layer.image=image;state.layers.push(layer);selectedId=layer.id;}e.target.value='';notify();};
  $('addTextBtn').onclick=()=>{const text=prompt('输入文字','新品上市');if(!text)return;const layer=normalizeLayer({type:'text',name:text.slice(0,16),text,x:state.canvas.width*.1,y:state.canvas.height*.42,w:state.canvas.width*.8,h:120,fontSize:72,color:'#202936'});state.layers.push(layer);selectedId=layer.id;notify();};
  $('deleteLayer').onclick=()=>{if(!selectedId)return;state.layers.splice(state.layers.findIndex(l=>l.id===selectedId),1);selectedId='';notify();};
  [['layerName','name'],['layerX','x'],['layerY','y'],['layerW','w'],['layerH','h'],['layerOpacity','opacity'],['textColor','color'],['fontSize','fontSize']].forEach(([id,key])=>$(id).oninput=e=>updateSelected({[key]:['x','y','w','h','opacity','fontSize'].includes(key)?Number(e.target.value):e.target.value}));
  canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*state.canvas.width;const y=(e.clientY-rect.top)/rect.height*state.canvas.height;const hit=state.layers.slice().reverse().find(l=>l.visible&&x>=l.x&&x<=l.x+l.w&&y>=l.y&&y<=l.y+l.h);if(!hit)return;selectedId=hit.id;drag={x,y,ox:hit.x,oy:hit.y};canvas.setPointerCapture(e.pointerId);render();});canvas.addEventListener('pointermove',e=>{if(!drag)return;const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*state.canvas.width;const y=(e.clientY-rect.top)/rect.height*state.canvas.height;const layer=selected();if(layer){layer.x=drag.ox+x-drag.x;layer.y=drag.oy+y-drag.y;render();}});canvas.addEventListener('pointerup',()=>{if(drag){drag=null;notify();}});
  $('zoomOut').onclick=()=>{zoom=Math.max(.1,zoom-.1);render();};$('zoomIn').onclick=()=>{zoom=Math.min(2,zoom+.1);render();};$('fitBtn').onclick=fit;window.addEventListener('resize',fit);window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();notify();}if(e.key==='Delete')$('deleteLayer').click();});
  $('exportBtn').onclick=()=>{render();post('output',{output:{kind:'image',source:canvas.toDataURL('image/png'),name:'poster.png',mime:'image/png',width:state.canvas.width,height:state.canvas.height}});const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='poster.png';a.click();};
  window.addEventListener('message',async e=>{if(!e.data||e.data.protocol!==protocol)return;const p=e.data.payload||{};if(e.data.type==='init'){if(p.state&&p.state.canvas){Object.assign(state.canvas,p.state.canvas);state.layers=(p.state.layers||[]).map(normalizeLayer);for(const l of state.layers)if(l.src)try{l.image=await loadImage(l.src);}catch{}selectedId=state.layers.at(-1)?.id||'';$('width').value=state.canvas.width;$('height').value=state.canvas.height;$('dpi').value=state.canvas.dpi||72;$('background').value=state.canvas.background;render();fit();}}});$('width').value=state.canvas.width;$('height').value=state.canvas.height;$('dpi').value=state.canvas.dpi;$('background').value=state.canvas.background;post('ready');render();setTimeout(fit,50);
})();
